kind = "web"
previewPath = "/3eyadahub/"
title = "3eyadahub"
version = "1.0.0"
id = "artifacts/3eyadahub"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/3eyadahub/" ]
localPort = 21496

[services.development]
run = "pnpm --filter @workspace/3eyadahub run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/3eyadahub", "run", "build" ]
publicDir = "artifacts/3eyadahub/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21496"
BASE_PATH = "/3eyadahub/"
